// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Логин",
                "parameters": [
                    {
                        "description": "Логин данные",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные регистрации",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/api/campaigns": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "campaigns"
                ],
                "summary": "Получить все кампании",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetAllCampaignsResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "campaigns"
                ],
                "summary": "Создать кампанию",
                "parameters": [
                    {
                        "description": "Данные кампании",
                        "name": "campaign",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCampaignResponse"
                        }
                    }
                }
            }
        },
        "/api/campaigns/{id}": {
            "delete": {
                "tags": [
                    "campaigns"
                ],
                "summary": "Удалить кампанию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID кампании",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteCampaignResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "campaigns"
                ],
                "summary": "Обновить статус кампании",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID кампании",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус кампании",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CampaignResponse"
                        }
                    }
                }
            }
        },
        "/api/clients": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Получить всех клиентов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetAllClientsResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Создать клиента",
                "parameters": [
                    {
                        "description": "Данные шаблона",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateClientResponse"
                        }
                    }
                }
            }
        },
        "/api/clients/{id}": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Обновить клиента",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID клиента",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные шаблона",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateClientResponse"
                        }
                    }
                }
            }
        },
        "/api/templates": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Получить все шаблоны",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetAllTemplatesResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Создать шаблон",
                "parameters": [
                    {
                        "description": "Данные шаблона",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTemplateResponse"
                        }
                    }
                }
            }
        },
        "/api/templates/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Получить шаблон по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID шаблона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetTemplateByIDResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "templates"
                ],
                "summary": "Удалить шаблон",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID шаблона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteTemplateResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Обновить шаблон",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID шаблона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные шаблона",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateTemplateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CampaignResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-10-10T10:00:00Z"
                },
                "created_by": {
                    "type": "integer",
                    "example": 2
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2023-10-10T10:00:00Z"
                },
                "segment": {
                    "type": "string",
                    "example": "sport"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "tpl_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.ClientResponse": {
            "type": "object",
            "properties": {
                "consent_flag": {
                    "type": "boolean",
                    "example": true
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-06-01T12:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "mirea@mail.ru"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "segment": {
                    "type": "string",
                    "example": "sport"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-11-05T12:00:00Z"
                }
            }
        },
        "dto.CreateCampaignRequest": {
            "type": "object",
            "required": [
                "created_by",
                "scheduled_at",
                "segment",
                "tpl_id"
            ],
            "properties": {
                "created_by": {
                    "type": "integer",
                    "example": 2
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2023-10-10T10:00:00Z"
                },
                "segment": {
                    "type": "string",
                    "example": "sport"
                },
                "tpl_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.CreateCampaignResponse": {
            "type": "object",
            "properties": {
                "campaign": {
                    "$ref": "#/definitions/dto.CampaignResponse"
                },
                "message": {
                    "type": "string",
                    "example": "кампания создана"
                }
            }
        },
        "dto.CreateClientRequest": {
            "type": "object",
            "required": [
                "email",
                "segment"
            ],
            "properties": {
                "consent_flag": {
                    "type": "boolean",
                    "example": true
                },
                "email": {
                    "type": "string",
                    "example": "mirea@mail.ru"
                },
                "segment": {
                    "type": "string",
                    "example": "sport"
                }
            }
        },
        "dto.CreateClientResponse": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/dto.ClientResponse"
                },
                "message": {
                    "type": "string",
                    "example": "клиент создан"
                }
            }
        },
        "dto.CreateTemplateRequest": {
            "type": "object",
            "required": [
                "html_body",
                "name"
            ],
            "properties": {
                "html_body": {
                    "type": "string",
                    "example": "\u003ch1\u003eHello\u003c/h1\u003e"
                },
                "name": {
                    "type": "string",
                    "example": "Welcome template"
                }
            }
        },
        "dto.CreateTemplateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "шаблон создан"
                },
                "template": {
                    "$ref": "#/definitions/dto.TemplateResponse"
                }
            }
        },
        "dto.DeleteCampaignResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "кампания удалена"
                }
            }
        },
        "dto.DeleteClientResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "клиент удалён"
                }
            }
        },
        "dto.DeleteTemplateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "шаблон удалён"
                }
            }
        },
        "dto.GetAllCampaignsResponse": {
            "type": "object",
            "properties": {
                "campaigns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CampaignResponse"
                    }
                }
            }
        },
        "dto.GetAllClientsResponse": {
            "type": "object",
            "properties": {
                "clients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ClientResponse"
                    }
                }
            }
        },
        "dto.GetAllTemplatesResponse": {
            "type": "object",
            "properties": {
                "templates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TemplateResponse"
                    }
                }
            }
        },
        "dto.GetTemplateByIDResponse": {
            "type": "object",
            "properties": {
                "template": {
                    "$ref": "#/definitions/dto.TemplateResponse"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "example": "user123"
                },
                "password": {
                    "type": "string",
                    "example": "pass123"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "успешный вход"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "login",
                "password",
                "role"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "example": "user123"
                },
                "password": {
                    "type": "string",
                    "example": "pass123"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "marketer",
                        "analyst",
                        "admin"
                    ],
                    "example": "marketer"
                }
            }
        },
        "dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "example": "user123"
                },
                "message": {
                    "type": "string",
                    "example": "пользователь создан"
                },
                "role": {
                    "type": "string",
                    "example": "marketer"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.TemplateResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-06-01T12:00:00Z"
                },
                "created_by": {
                    "type": "integer",
                    "example": 18
                },
                "html_body": {
                    "type": "string",
                    "example": "\u003ch1\u003eHello\u003c/h1\u003e"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Welcome template"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-06-01T12:00:00Z"
                },
                "updated_by": {
                    "type": "integer",
                    "example": 18
                }
            }
        },
        "dto.UpdateCampaignRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "dto.UpdateClientRequest": {
            "type": "object",
            "properties": {
                "consent_flag": {
                    "type": "boolean",
                    "example": true
                },
                "email": {
                    "type": "string",
                    "example": "mirea@mail.ru"
                },
                "segment": {
                    "type": "string",
                    "example": "sport"
                }
            }
        },
        "dto.UpdateClientResponse": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/dto.ClientResponse"
                },
                "message": {
                    "type": "string",
                    "example": "клиент обновлён"
                }
            }
        },
        "dto.UpdateTemplateRequest": {
            "type": "object",
            "properties": {
                "html_body": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateTemplateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "шаблон обновлён"
                },
                "template": {
                    "$ref": "#/definitions/dto.TemplateResponse"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "security": [
        {
            "BearerAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Email Campaign API",
	Description:      "API для конструктора email-рассылок",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
