basePath: /
definitions:
  dto.CreateTemplateRequest:
    properties:
      html_body:
        example: <h1>Hello</h1>
        type: string
      name:
        example: Welcome template
        type: string
    required:
    - html_body
    - name
    type: object
  dto.CreateTemplateResponse:
    properties:
      message:
        example: шаблон создан
        type: string
      template:
        $ref: '#/definitions/dto.TemplateResponse'
    type: object
  dto.DeleteTemplateResponse:
    properties:
      message:
        example: шаблон удалён
        type: string
    type: object
  dto.GetAllTemplatesResponse:
    properties:
      templates:
        items:
          $ref: '#/definitions/dto.TemplateResponse'
        type: array
    type: object
  dto.GetTemplateByIDResponse:
    properties:
      template:
        $ref: '#/definitions/dto.TemplateResponse'
    type: object
  dto.TemplateResponse:
    properties:
      created_at:
        example: "2024-06-01T12:00:00Z"
        type: string
      created_by:
        example: 18
        type: integer
      html_body:
        example: <h1>Hello</h1>
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Welcome template
        type: string
      updated_at:
        example: "2024-06-01T12:00:00Z"
        type: string
      updated_by:
        example: 18
        type: integer
    type: object
  dto.UpdateTemplateRequest:
    properties:
      html_body:
        type: string
      name:
        type: string
    type: object
  dto.UpdateTemplateResponse:
    properties:
      message:
        example: шаблон обновлён
        type: string
      template:
        $ref: '#/definitions/dto.TemplateResponse'
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для конструктора email-рассылок
  title: Email Campaign API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Логин данные
        in: body
        name: input
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Логин
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные регистрации
        in: body
        name: input
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Регистрация пользователя
      tags:
      - auth
  /api/templates:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAllTemplatesResponse'
      summary: Получить все шаблоны
      tags:
      - templates
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные шаблона
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTemplateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateTemplateResponse'
      summary: Создать шаблон
      tags:
      - templates
  /api/templates/{id}:
    delete:
      parameters:
      - description: ID шаблона
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DeleteTemplateResponse'
      summary: Удалить шаблон
      tags:
      - templates
    get:
      parameters:
      - description: ID шаблона
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetTemplateByIDResponse'
      summary: Получить шаблон по ID
      tags:
      - templates
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID шаблона
        in: path
        name: id
        required: true
        type: integer
      - description: Данные шаблона
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTemplateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateTemplateResponse'
      summary: Обновить шаблон
      tags:
      - templates
security:
- BearerAuth: []
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
